<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>QPK_Keynote_Manager</RootNamespace>
		<AssemblyName>QPKFindReplace</AssemblyName>
		<UseWPF>true</UseWPF>

		<LangVersion>7.3</LangVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>
		<DefineConstants>REVIT2024</DefineConstants>

		<Configurations>Debug;Release;x86</Configurations>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Resources\**" />
	  <EmbeddedResource Remove="Resources\**" />
	  <None Remove="Resources\**" />
	  <Page Remove="Resources\**" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="RevitAPI">
			<HintPath>..\..\..\..\..\..\Program Files\Autodesk\Revit 2024\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI">
			<HintPath>..\..\..\..\..\..\Program Files\Autodesk\Revit 2024\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Import Project="..\QPKFindReplaceShared\QPKFindReplaceShared.projitems" Label="Shared" />

</Project>